### ISSUE TITLE
"Could not get data" после последнего обновления

### ISSUE THREAD

**Issue by pznamenskii** [yandex/pogoda-home-assistant#34]
### В чем проблема?

интеграция не может получить данные от сервиса. ключ не менялся (до обновления на версию 0.0.4 работал).
![api](https://github.com/user-attachments/assets/e8ed053c-7687-439b-a75c-101a79ab70d1)

Could not get data. Check your API key in Yandex developer portal. It may took up to 5 minutes for updating key settings at Yandex side.
![err](https://github.com/user-attachments/assets/b11e99d4-45d2-410a-81d9-ab0ac00bc3cd)

### Какая версия Home Assistant используется?

2024.10.2

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

### Приложите лог, если в логе есть сообщение об ошибке, trace либо что-нибудь полезное

```txt
2024-10-17 22:07:58.808 INFO (MainThread) [homeassistant.components.sensor] Setting up yandex_pogoda.sensor
2024-10-17 22:07:58.815 INFO (MainThread) [homeassistant.components.weather] Setting up yandex_pogoda.weather
2024-10-17 22:07:58.816 INFO (MainThread) [custom_components.yandex_pogoda.updater] Sending API request
2024-10-17 22:07:58.871 ERROR (MainThread) [custom_components.yandex_pogoda.updater] Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/graphql/query) [429 None]>
<CIMultiDictProxy('Transfer-Encoding': 'chunked')>

2024-10-17 22:07:58.872 DEBUG (MainThread) [custom_components.yandex_pogoda.updater] Finished fetching Yandex Pogoda  Legostaeva updater data in 0.056 seconds (success: False)
2024-10-17 22:07:58.873 DEBUG (MainThread) [custom_components.yandex_pogoda.weather] _handle_coordinator_update: self._hourly_forecast=[]
2024-10-17 22:07:58.874 ERROR (MainThread) [homeassistant.components.weather] Error adding entity weather.yandex_legostaeva for domain weather with platform yandex_pogoda
Traceback (most recent call last):
  File "/config/custom_components/yandex_pogoda/updater.py", line 367, in request
    assert response.status == 200
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_pogoda/updater.py", line 282, in update
    data = await self._get_weather_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_pogoda/updater.py", line 272, in _get_weather_data
    rs = await self.request(session, self.__api_key, self._lat, self._lon)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/yandex_pogoda/updater.py", line 370, in request
    raise aiohttp.ClientError(response.status, await response.text()) from e
aiohttp.client_exceptions.ClientError: (429, 'limited')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/yandex_pogoda/weather.py", line 130, in async_added_to_hass
    await self.coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: (429, 'limited')
```

**Comment by dimastark** [comment]
Должно починиться, проверьте, пожалуйста.

**Comment by pznamenskii** [comment]
подтверждаю. причём вчера не работало даже в песочнице сервиса - писал в поддержку им.
